name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: idawnlight
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: idawnlight/php
        cache: idawnlight/php
        auto_tag: true
